BEGIN;

ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS familia_marca VARCHAR;

ALTER TABLE ventas_historicas
    ADD COLUMN IF NOT EXISTS margen_bruto_eur DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS margen_bruto_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS margen_destino_eur DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS margen_destino_pct DOUBLE PRECISION;

COMMIT;
