import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { GLOSARIO } from '../content/glosario';
import type { GlossaryKey } from '../content/glosario';

const glossaryKeys: GlossaryKey[] = ['senal', 'episodio', 'severidad', 'impacto_realizado', 'impacto_en_riesgo', 'impacto_capital', 'naturaleza', 'relacion', 'evidencia', 'evidencia_degradada', 'investigacion', 'decision', 'supresion', 'preparacion_datos'];
const index = [
  ['que-hace', 'Qué hace este sistema'],
  ['rutina', 'Tu rutina'],
  ['glosario', 'Glosario'],
  ['no-hace', 'Qué no hace'],
] as const;

const Section = ({ id, title, children }: { id: string; title: string; children: React.ReactNode }) => <section id={id} className="scroll-mt-6 border-b border-black/[0.08] py-8 last:border-0 dark:border-slate-800"><h2 className="text-[24px] font-semibold tracking-[-.02em] text-[#1d1d1f] dark:text-white">{title}</h2><div className="mt-5 space-y-4 text-[15px] leading-7 text-[#424245] dark:text-slate-300">{children}</div></section>;

export const AiControlGuide = () => <div className="control-apple min-h-screen flex-1 overflow-auto bg-[#f5f5f7] p-4 dark:bg-brand-dark md:p-8"><div className="mx-auto max-w-[1200px]">
  <Link to="/ai-control" className="mb-5 inline-flex items-center gap-2 text-[13px] font-medium text-[#0071e3] dark:text-brand-cyan"><ArrowLeft size={15} />Volver a Control IA</Link>
  <header className="rounded-[24px] bg-white p-6 shadow-sm dark:bg-slate-900 md:p-8"><p className="text-[13px] font-medium text-[#0071e3]">Guía de Control IA</p><h1 className="mt-2 text-[32px] font-semibold tracking-[-.03em] text-[#1d1d1f] dark:text-white">Entender, decidir y aprender</h1><p className="mt-2 max-w-2xl text-[15px] text-[#6e6e73] dark:text-slate-400">Una referencia para usar el sistema cada día y saber cuándo confiar en sus resultados.</p></header>
  <div className="mt-6 grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="h-fit rounded-[18px] bg-white p-4 shadow-sm dark:bg-slate-900 lg:sticky lg:top-6"><p className="px-2 pb-2 text-[12px] font-medium text-[#6e6e73]">En esta guía</p><nav className="space-y-1" aria-label="Índice de la guía">{index.map(([id, label]) => <a key={id} href={`#${id}`} className="block rounded-[9px] px-2 py-2 text-[13px] text-[#424245] hover:bg-[#f5f5f7] hover:text-[#0071e3] focus-visible:ring-2 focus-visible:ring-[#0071e3] dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-brand-cyan">{label}</a>)}</nav></aside>
    <main className="rounded-[24px] bg-white px-6 shadow-sm dark:bg-slate-900 md:px-10"><Section id="que-hace" title="Qué hace este sistema"><p>Cada madrugada se ejecutan cuatro pasos.</p><p><strong>Primero se revisa la calidad de los datos.</strong> Costes que faltan, ventas sin cliente, inventario desactualizado. Si algo está mal, se avisa antes de analizar nada.</p><p><strong>Después, tres analistas revisan su área.</strong> Lucía mira las ventas: caídas por familia, por producto y por comercial, clientes que llevan demasiado tiempo sin comprar, precios que bailan demasiado entre clientes. María mira el inventario: roturas de stock en los productos que más rotan, coberturas que no llegan al plazo de reposición, stock inmovilizado. Mattia mira el dinero: márgenes que se erosionan, productos vendidos por debajo de coste, dependencia excesiva de pocos productos.</p><p><strong>Luego se cruzan los hallazgos.</strong> Lo que pertenece al mismo hecho se agrupa en un episodio, y se marca qué explica qué. Esta parte es aritmética pura, no interviene la IA.</p><p><strong>Por último, un cuarto analista consolida</strong> los episodios más relevantes y propone hasta tres decisiones.</p><p>Los cálculos son deterministas: los hace la base de datos y salen siempre iguales. La IA solo redacta la explicación y no puede modificar ni una cifra. Si un informe cita un número que no cuadra con la evidencia, no se publica.</p></Section>
      <Section id="rutina" title="Tu rutina"><p><strong>Cada mañana, cinco minutos.</strong><br />Mira los tres contadores de la cabecera: qué es nuevo, qué ha empeorado y qué se ha resuelto. Repasa los episodios de arriba. De cada uno, haz una sola cosa: descartarlo con un motivo, pedir investigación o crear una decisión. No dejes nada sin tocar: un episodio que llevas cinco días ignorando es ruido, y hay que decirle al sistema que lo es.</p><p><strong>Cada lunes, veinte minutos.</strong><br />Llega el resumen semanal por correo. Revisa las decisiones con plazo vencido y ciérralas anotando el resultado, aunque el resultado sea que no funcionó. Mira las oportunidades detectadas, que es la parte que casi nadie mira. Y echa un vistazo a la pantalla de calidad: si un detector te está dando muchos falsos positivos, ajústalo o desactívalo.</p><p><strong>Cada mes, una hora.</strong><br />Repasa las reglas de negocio: plazos de reposición, márgenes objetivo, clientes estratégicos, productos discontinuados. Cambian, y cuando están mal el sistema analiza mal.</p></Section>
      <Section id="glosario" title="Glosario"><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-[14px]"><thead className="border-b border-black/[0.08] text-[#6e6e73] dark:border-slate-800"><tr><th className="pb-3 pr-5 font-medium">Término</th><th className="pb-3 font-medium">Definición</th></tr></thead><tbody>{glossaryKeys.map((key) => <tr key={key} className="border-b border-black/[0.06] align-top dark:border-slate-800"><td className="py-3 pr-5 font-medium text-[#1d1d1f] dark:text-white">{GLOSARIO[key].termino}</td><td className="py-3">{GLOSARIO[key].definicion}</td></tr>)}</tbody></table></div></Section>
      <Section id="no-hace" title="Qué no hace"><p>No predice el futuro. Compara períodos y detecta cambios; no hace previsiones de demanda.</p><p>No conoce el contexto que no le has dado. Si una caída se debe a que un cliente cerró por obras, no lo sabe hasta que se lo dices o lo anotas en las reglas de negocio.</p><p>No sustituye tu criterio. Señala y cuantifica; decidir sigue siendo tuyo.</p><p>No inventa datos. Si falta una fuente, lo dice y no analiza esa área. Es una limitación deliberada.</p><p>No es un chat que responda a cualquier cosa. Los analistas hablan de lo que han detectado y de la evidencia que lo respalda.</p></Section>
    </main></div>
</div></div>;
