import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Bar, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowRight, Loader2 } from 'lucide-react';
import { getMarginBridge, getMarginOverview, getMarginSignals } from '../services/api';
import type { MarginBridge, MarginMetric, MarginOverview, MarginSignal, MarginWindow } from '../services/api';
import { GlossaryTooltip } from '../components/GlossaryTooltip';

const euro = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 });
const pct = new Intl.NumberFormat('es-ES', { maximumFractionDigits: 1, minimumFractionDigits: 1 });
const windows: Array<[MarginWindow, string]> = [['30d', '30 días'], ['90d', '90 días'], ['12m', '12 meses']];

const MetricCard = ({ title, value, detail, change, term }: { title: string; value: string; detail: string; change?: number | null; term?: 'mg' | 'mgd' }) => <article className="rounded-[20px] border border-black/[0.08] bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="flex items-center text-[12px] font-medium text-[#6e6e73]">{title}{term && <GlossaryTooltip term={term} />}</p><p className="ai-tnum mt-2 text-[24px] font-semibold tracking-[-0.03em] text-[#1d1d1f] dark:text-white">{value}</p><p className="ai-tnum mt-2 text-[12px] text-[#6e6e73]">{detail}{change !== undefined && change !== null ? ` · ${change >= 0 ? '+' : ''}${pct.format(change)}` : ''}</p></article>;

export const Marginality = () => {
  const [params, setParams] = useSearchParams();
  const metric = (params.get('metrica') === 'mg' ? 'mg' : 'mgd') as MarginMetric;
  const window = (['30d', '90d', '12m'].includes(params.get('ventana') || '') ? params.get('ventana') : '90d') as MarginWindow;
  const [overview, setOverview] = useState<MarginOverview | null>(null); const [bridge, setBridge] = useState<MarginBridge | null>(null); const [signals, setSignals] = useState<MarginSignal[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.resolve().then(() => { setLoading(true); return Promise.all([getMarginOverview(window), getMarginBridge(metric, window), getMarginSignals()]); }).then(([data, decomposition, signalData]) => { setOverview(data); setBridge(decomposition); setSignals(signalData.senales); setError(null); }).catch(() => setError('No se pudo cargar la analítica de marginalidad.')).finally(() => setLoading(false)); }, [metric, window]);
  const series = useMemo(() => overview?.serie_diaria.map(row => ({ ...row, fecha: new Date(`${row.fecha}T00:00:00`).toLocaleDateString('es-ES', { day: '2-digit', month: 'short' }), margen: metric === 'mg' ? row.mg_eur : row.mgd_eur, tasa: metric === 'mg' ? row.mg_pct : row.mgd_pct })) ?? [], [metric, overview]);
  const set = (key: 'metrica' | 'ventana', value: string) => { const next = new URLSearchParams(params); next.set(key, value); setParams(next); };
  const actual = overview?.actual;
  return <div className="control-apple min-h-screen flex-1 overflow-auto bg-[#f5f5f7] p-4 dark:bg-brand-dark md:p-8"><main className="mx-auto max-w-[1440px]">
    <header className="rounded-[24px] border border-black/[0.08] bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><p className="text-[13px] font-medium text-[#0071e3] dark:text-brand-cyan">Análisis financiero</p><div className="mt-2 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-[32px] font-semibold tracking-[-0.03em] text-[#1d1d1f] dark:text-white">Marginalidad</h1><p className="mt-2 text-[14px] text-[#6e6e73]">Margen ponderado, concentración y variación sobre datos reales.</p></div><div className="flex flex-wrap gap-2"><div className="inline-flex rounded-[10px] bg-[#f5f5f7] p-1 dark:bg-slate-800">{(['mg', 'mgd'] as MarginMetric[]).map(value => <button key={value} onClick={() => set('metrica', value)} className={`min-h-9 rounded-[8px] px-3 text-[13px] font-medium ${metric === value ? 'bg-white text-[#1d1d1f] shadow-sm dark:bg-slate-700 dark:text-white' : 'text-[#6e6e73]'}`}>{value.toUpperCase()}</button>)}</div><div className="inline-flex rounded-[10px] bg-[#f5f5f7] p-1 dark:bg-slate-800">{windows.map(([value, label]) => <button key={value} onClick={() => set('ventana', value)} className={`min-h-9 rounded-[8px] px-3 text-[13px] font-medium ${window === value ? 'bg-white text-[#1d1d1f] shadow-sm dark:bg-slate-700 dark:text-white' : 'text-[#6e6e73]'}`}>{label}</button>)}</div></div></div></header>
    {loading ? <div className="flex min-h-80 items-center justify-center text-[#6e6e73]"><Loader2 className="mr-3 animate-spin" />Calculando marginalidad…</div> : error || !actual ? <div className="mt-6 rounded-[16px] border border-red-200 bg-red-50 p-5 text-red-700">{error}</div> : <><p className="mt-5 text-[12px] text-[#6e6e73]">Período {overview?.periodo.inicio} a {overview?.periodo.fin} · comparación equivalente anterior</p><section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><MetricCard title="Ventas" value={euro.format(actual.ventas_eur || 0)} detail="Ventas netas del período" change={overview?.variacion.ventas_eur} /><MetricCard title="MG" value={`${euro.format(actual.mg_eur || 0)} · ${actual.mg_pct === null ? '—' : `${pct.format(actual.mg_pct)} %`}`} detail="Margen bruto ponderado" change={overview?.variacion.mg_pct} term="mg" /><MetricCard title="MGD" value={`${euro.format(actual.mgd_eur || 0)} · ${actual.mgd_pct === null ? '—' : `${pct.format(actual.mgd_pct)} %`}`} detail="Margen puesto en destino ponderado" change={overview?.variacion.mgd_pct} term="mgd" /><MetricCard title="MG − MGD" value={euro.format(actual.diferencia_eur || 0)} detail={`${actual.diferencia_pp === null ? '—' : `${pct.format(actual.diferencia_pp)} puntos`} consumidos entre origen y destino`} change={overview?.variacion.diferencia_pp} /><MetricCard title="Margen negativo" value={String(actual.sku_negativos || 0)} detail={`${euro.format(actual.margen_negativo_eur || 0)} en SKU afectados`} /><MetricCard title="Top 10 MGD" value={overview?.top10_mgd_positivo_pct === null ? '—' : `${pct.format(overview.top10_mgd_positivo_pct)} %`} detail="sobre MGD positivo" /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><article className="rounded-[20px] border border-black/[0.08] bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-[17px] font-semibold text-[#1d1d1f] dark:text-white">Evolución comercial</h2><p className="mt-1 text-[13px] text-[#6e6e73]">Euros de {metric.toUpperCase()} y su tasa ponderada por día.</p><div className="mt-5 h-[320px] min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 1, height: 320 }}><ComposedChart data={series}><XAxis dataKey="fecha" tick={{ fontSize: 11 }} minTickGap={28} /><YAxis yAxisId="euros" tickFormatter={(value) => `${Math.round(value / 1000)}k`} tick={{ fontSize: 11 }} /><YAxis yAxisId="pct" orientation="right" tickFormatter={(value) => `${value}%`} tick={{ fontSize: 11 }} /><Tooltip /><Bar yAxisId="euros" dataKey="margen" name={`${metric.toUpperCase()} €`} fill="#0071e3" radius={[4, 4, 0, 0]} /><Line yAxisId="pct" dataKey="tasa" name="tasa" stroke="#f59e0b" strokeWidth={2} dot={false} /></ComposedChart></ResponsiveContainer></div></article><article className="rounded-[20px] border border-black/[0.08] bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-[17px] font-semibold text-[#1d1d1f] dark:text-white">Puente de variación</h2><p className="mt-1 text-[13px] text-[#6e6e73]">La variación se separa en precio, coste y mix residual.</p><div className="mt-6 space-y-4">{[['Precio', bridge?.efecto_precio_eur], ['Coste', bridge?.efecto_coste_eur], ['Mix residual', bridge?.efecto_mix_residual_eur]].map(([label, value]) => <div key={String(label)}><div className="flex justify-between text-[13px]"><span>{label}</span><strong className="ai-tnum">{euro.format(Number(value || 0))}</strong></div><div className="mt-2 h-2 rounded bg-[#f5f5f7] dark:bg-slate-800"><div className={`h-2 rounded ${Number(value) < 0 ? 'bg-red-500' : 'bg-[#0071e3]'}`} style={{ width: `${Math.min(100, Math.abs(Number(value || 0)) / Math.max(1, Math.abs(bridge?.delta_margen_eur || 0)) * 100)}%` }} /></div></div>)}</div><p className="mt-5 rounded-[10px] bg-[#f5f5f7] p-3 text-[12px] text-[#6e6e73] dark:bg-slate-800">{bridge?.nota}</p></article></section>
    <section className="mt-6 rounded-[20px] border border-black/[0.08] bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div><h2 className="text-[17px] font-semibold text-[#1d1d1f] dark:text-white">Señales activas de margen</h2><p className="mt-1 text-[13px] text-[#6e6e73]">Hallazgos de Control IA reutilizados, sin recalcular detectores.</p></div><Link to="/ai-control" className="text-[13px] font-medium text-[#0071e3] dark:text-brand-cyan">Control IA</Link></div>{signals.length ? <div className="mt-4 divide-y divide-black/[0.06] dark:divide-slate-800">{signals.slice(0, 5).map(signal => <Link key={signal.id} to={`/ai-control/senal/${signal.id}`} className="flex items-center justify-between gap-4 py-3 text-[13px]"><span className="flex items-center gap-2"><AlertTriangle size={15} className="text-amber-500" />{signal.detector} · {signal.entidad_id}</span><span className="ai-tnum text-[#6e6e73]">Severidad {signal.severidad} <ArrowRight className="ml-1 inline" size={14} /></span></Link>)}</div> : <p className="mt-5 text-[13px] text-[#6e6e73]">No hay señales activas de margen en este momento.</p>}</section></>}
  </main></div>;
};
