import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { getMarginEntity } from '../services/api';
import type { MarginEntity as MarginEntityData } from '../services/api';

const euro = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 });
const pct = new Intl.NumberFormat('es-ES', { maximumFractionDigits: 1 });

export const MarginEntity = () => {
  const { tipo = '', id = '' } = useParams(); const [data, setData] = useState<MarginEntityData | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { getMarginEntity(tipo, id).then(setData).catch(() => setError('No se pudo cargar la ficha de esta entidad.')); }, [tipo, id]);
  return <div className="control-apple min-h-screen flex-1 overflow-auto bg-[#f5f5f7] p-4 dark:bg-brand-dark md:p-8"><main className="mx-auto max-w-[1100px]"><Link to="/marginalidad" className="mb-5 inline-flex items-center gap-2 text-[13px] font-medium text-[#0071e3] dark:text-brand-cyan"><ArrowLeft size={15} />Volver a Marginalidad</Link>{error ? <p className="rounded-[14px] bg-red-50 p-4 text-red-700">{error}</p> : !data ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="animate-spin" /></div> : <><header className="rounded-[20px] bg-white p-6 dark:bg-slate-900"><p className="text-[12px] text-[#6e6e73]">{data.entidad_tipo}</p><h1 className="mt-2 text-[28px] font-semibold text-[#1d1d1f] dark:text-white">{data.entidad_id}</h1><p className="mt-2 text-[13px] text-[#6e6e73]">Serie mensual de los últimos doce meses con ventas, MG y MGD ponderados.</p></header><section className="mt-5 overflow-x-auto rounded-[20px] bg-white p-5 dark:bg-slate-900"><table className="w-full min-w-[700px] text-left text-[13px]"><thead className="border-b text-[#6e6e73]"><tr><th className="p-3">Mes</th><th className="p-3 text-right">Ventas</th><th className="p-3 text-right">MG</th><th className="p-3 text-right">MG %</th><th className="p-3 text-right">MGD</th><th className="p-3 text-right">MGD %</th></tr></thead><tbody>{data.serie_mensual.map(row => <tr key={row.mes} className="border-b border-black/[0.06] dark:border-slate-800"><td className="p-3">{row.mes}</td><td className="ai-tnum p-3 text-right">{euro.format(row.ventas_eur)}</td><td className="ai-tnum p-3 text-right">{euro.format(row.mg_eur)}</td><td className="ai-tnum p-3 text-right">{row.mg_pct === null ? '—' : `${pct.format(row.mg_pct)} %`}</td><td className="ai-tnum p-3 text-right">{euro.format(row.mgd_eur)}</td><td className="ai-tnum p-3 text-right">{row.mgd_pct === null ? '—' : `${pct.format(row.mgd_pct)} %`}</td></tr>)}</tbody></table></section><section className="mt-5 rounded-[20px] bg-white p-5 dark:bg-slate-900"><h2 className="font-semibold text-[#1d1d1f] dark:text-white">Señales activas</h2>{data.senales_activas.length ? data.senales_activas.map(signal => <Link key={signal.id} to={`/ai-control/senal/${signal.id}`} className="mt-3 block text-[13px] text-[#0071e3] dark:text-brand-cyan">{signal.detector} · severidad {signal.severidad}</Link>) : <p className="mt-3 text-[13px] text-[#6e6e73]">No hay señales activas vinculadas.</p>}</section></>}</main></div>;
};
